# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  basicasptutorial:
    image: basicasptutorial    
    build:
      context: .
      dockerfile: BasicASPTutorial/Dockerfile    
    ports:
      - 8083:8083
    depends_on: 
      - database
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
      - DBHOST=database
    restart: always    
     