name: docker-compose-actions-workflow

on: 
  push:
    branches: [ "main1" ]
    tags:
      - v1.*.*
jobs:
  build-run:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run Docker Compose
      run: docker-compose up -d --build
